-- Ciphertext-only mailbox for cross-network review sharing.
-- The server never sees plaintext: bundle/response are AES-256-GCM ciphertext (base64url)
-- and the AES key lives only in the share link fragment. RLS denies all direct access;
-- the SECURITY DEFINER RPCs below are the only entry points, so rows can't be enumerated.
--
-- The row id is generated by the client and doubles as both the bundle locator and the
-- response mailbox. The inline tier never calls create_share (its bundle rides in the URL);
-- its row is born only if the reviewer responds, via the upsert in put_response.

create table if not exists public.shares (
  id uuid primary key,
  bundle text,
  response text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.shares enable row level security;
-- No policies -> deny-all for anon/authenticated. Access is via the RPCs only.

-- ~8 MB of base64 (~6 MB raw) is the ceiling; larger payloads should never reach here.
create or replace function public.create_share(share_id uuid, bundle text, ttl_days int default 14)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if length(bundle) > 8000000 then
    raise exception 'bundle too large';
  end if;
  insert into public.shares (id, bundle, expires_at)
  values (share_id, bundle, now() + make_interval(days => greatest(1, least(ttl_days, 90))))
  on conflict (id) do update set bundle = excluded.bundle, expires_at = excluded.expires_at;
end;
$$;

create or replace function public.get_bundle(share_id uuid)
returns text
language sql
security definer
set search_path = public
as $$
  select bundle from public.shares where id = share_id and expires_at > now();
$$;

-- Upsert so the inline tier's mailbox row is created on first response.
create or replace function public.put_response(share_id uuid, resp text, ttl_days int default 14)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if length(resp) > 8000000 then
    raise exception 'response too large';
  end if;
  insert into public.shares (id, response, expires_at)
  values (share_id, resp, now() + make_interval(days => greatest(1, least(ttl_days, 90))))
  on conflict (id) do update set response = excluded.response;
end;
$$;

create or replace function public.get_response(share_id uuid)
returns text
language sql
security definer
set search_path = public
as $$
  select response from public.shares where id = share_id and expires_at > now();
$$;

revoke all on function public.create_share(uuid, text, int) from public;
revoke all on function public.get_bundle(uuid) from public;
revoke all on function public.put_response(uuid, text, int) from public;
revoke all on function public.get_response(uuid) from public;
grant execute on function public.create_share(uuid, text, int) to anon, authenticated;
grant execute on function public.get_bundle(uuid) to anon, authenticated;
grant execute on function public.put_response(uuid, text, int) to anon, authenticated;
grant execute on function public.get_response(uuid) to anon, authenticated;

-- Daily purge of expired shares, replacing the Vercel cron cleanup.
create extension if not exists pg_cron;
select cron.schedule('purge-expired-shares', '0 3 * * *', $$delete from public.shares where expires_at < now()$$);
